ebs-cryptolib: cryptolib/aes/aes_keyschedule.c File Reference
aes_keyschedule.c File Reference
#include <stdint.h>
#include "aes.h"
#include "aes_keyschedule.h"
#include "aes_sbox.h"
#include <string.h>
#include <platform/romem.h>
Macros
#define aes_rc_T_p ROMEM_TABLE_P(rc_tab)
Functions
void aes_init (const void *key, uint16_t keysize_b, aes_genctx_t *ctx)
initialize the keyschedule
void aes128_init (const void *key, aes128_ctx_t *ctx)
initialize the keyschedule for 128 bit key
void aes192_init (const void *key, aes192_ctx_t *ctx)
initialize the keyschedule for 192 bit key
void aes256_init (const void *key, aes256_ctx_t *ctx)
initialize the keyschedule for 256 bit key
Variables
const uint8_t rc_tab[] ROMEM
Detailed Description
\email bg@ne.nosp@m.rile.nosp@m.x.org
Author
Daniel Otte
Date
2008-12-30 \license GPLv3 or later
Definition in file aes_keyschedule.c.
Function Documentation
aes128_init()
void aes128_init (const void * key, aes128_ctx_t * ctx)
initialize the keyschedule for 128 bit key
This function computes the keyschedule from a given 128 bit key and stores it in the context variable
Parameters
key pointer to the key material
ctx pointer to the context where the keyschedule should be stored
Definition at line 88 of file aes_keyschedule.c.
References aes_init().
aes192_init()
void aes192_init (const void * key, aes192_ctx_t * ctx)
initialize the keyschedule for 192 bit key
This function computes the keyschedule from a given 192 bit key and stores it in the context variable
Parameters
key pointer to the key material
ctx pointer to the context where the keyschedule should be stored
Definition at line 93 of file aes_keyschedule.c.
References aes_init().
aes256_init()
void aes256_init (const void * key, aes256_ctx_t * ctx)
initialize the keyschedule for 256 bit key
This function computes the keyschedule from a given 256 bit key and stores it in the context variable
Parameters
key pointer to the key material
ctx pointer to the context where the keyschedule should be stored
Definition at line 98 of file aes_keyschedule.c.
References aes_init().
aes_init()
void aes_init (const void * key, uint16_t keysize_b, aes_genctx_t * ctx)
initialize the keyschedule
This function computes the keyschedule from a given key with a given length and stores it in the context variable
Parameters
key pointer to the key material
keysize_b length of the key in bits (valid are 128, 192 and 256)
ctx pointer to the context where the keyschedule should be stored
Definition at line 52 of file aes_keyschedule.c.
Referenced by aes128_init(), aes192_init(), and aes256_init().
Variable Documentation
ROMEM
const uint8_t rc_tab [] ROMEM
Initial value:
= { 0x01, 0x02, 0x04, 0x08,
        0x10, 0x20, 0x40, 0x80,
        0x1b, 0x36 }
Definition at line 48 of file aes_keyschedule.c.