ebs-cryptolib: cryptolib/entropium/entropium.h File Reference
entropium.h File Reference
This file contains the declarations for the pseudo-random-number generator.
#include <stdint.h>
Macros
#define ENTROPIUM_RANDOMBLOCK_SIZE 32 /* bytes */
Functions
void entropium_addEntropy (unsigned length_b, const void *data)
add entropy to the prng
void entropium_getRandomBlock (void *b)
generate a fixed size block of random data
uint8_t entropium_getRandomByte (void)
get a single byte of random data
void entropium_fillBlockRandom (void *block, unsigned length_B)
get a block of random data
Detailed Description
This file contains the declarations for the pseudo-random-number generator.
File: entropium.h Author: Daniel Otte Date: 23.07.2006 License: GPL Description: This file contains the declarations for the pseudo-random-number generator.
Author
Daniel Otte
Date
23.07.2006 \license GPLv3 or later
Definition in file entropium.h.
Function Documentation
entropium_addEntropy()
void entropium_addEntropy (unsigned length_b, const void * data)
add entropy to the prng
This function adds data to the internal entropy pool
Parameters
length_b length of the data block in bits
data pointer to the data
Definition at line 68 of file entropium.c.
References rndCore, sha256_init(), sha256_lastBlock(), and sha256_nextBlock().
entropium_fillBlockRandom()
void entropium_fillBlockRandom (void * block, unsigned length_B)
get a block of random data
This function writes random data extracted from the entropy pool in the supplied buffer. It shares a internal buffer with the entropium_getRandomByte() function.
Parameters
block pointer to the buffer where the random data goes
length_B number of bytes to be written to the buffer
Definition at line 119 of file entropium.c.
entropium_getRandomBlock()
void entropium_getRandomBlock (void * b)
generate a fixed size block of random data
This function writes 32 bytes of random extracted from the entropy pool in the supplied buffer.
Parameters
b buffer where the random data gets written
Definition at line 88 of file entropium.c.
References rndCore, sha256_init(), and sha256_lastBlock().
Referenced by entropium_getRandomByte().
entropium_getRandomByte()
uint8_t entropium_getRandomByte (void)
get a single byte of random data
This function utilizes a internal buffer which gets automatically filled again.
Returns
a byte of random data
Definition at line 108 of file entropium.c.
References entropium_getRandomBlock().