ebs-cryptolib: cryptolib/sha256/sha256.h File Reference
sha256.h File Reference
#include <stdint.h>
Data Structures
struct sha256_ctx_t
Macros
#define __LITTLE_ENDIAN__
#define SHA256_HASH_BITS 256
#define SHA256_HASH_BYTES (SHA256_HASH_BITS / 8)
#define SHA256_BLOCK_BITS 512
#define SHA256_BLOCK_BYTES (SHA256_BLOCK_BITS / 8)
Typedefs
typedef uint8_t sha256_hash_t[SHA256_HASH_BYTES]
SHA-256 hash value type.
Functions
void sha256_init (sha256_ctx_t *state)
sh256_init initialises a sha256 context for hashing. sh256_init c initialises the given sha256 context for hashing
void sha256_nextBlock (sha256_ctx_t *state, const void *block)
update the context with a given block
void sha256_lastBlock (sha256_ctx_t *state, const void *block, uint16_t length_b)
function to process the last block being hashed
void sha256_ctx2hash (sha256_hash_t *dest, const sha256_ctx_t *state)
convert the hash state into the hash value This function reads the context and writes the hash value to the destination
void sha256 (sha256_hash_t *dest, const void *msg, uint32_t length_b)
simple SHA-256 hashing function for direct hashing
Detailed Description
Author
Daniel Otte
Date
2006-05-16 \license GPLv3 or later
Definition in file sha256.h.
Macro Definition Documentation
SHA256_BLOCK_BITS
#define SHA256_BLOCK_BITS 512
defines the size of a SHA-256 input block in bits
Definition at line 53 of file sha256.h.
SHA256_BLOCK_BYTES
#define SHA256_BLOCK_BYTES (SHA256_BLOCK_BITS / 8)
defines the size of a SHA-256 input block in bytes
Definition at line 54 of file sha256.h.
SHA256_HASH_BITS
#define SHA256_HASH_BITS 256
defines the size of a SHA-256 hash value in bits
Definition at line 51 of file sha256.h.
SHA256_HASH_BYTES
#define SHA256_HASH_BYTES (SHA256_HASH_BITS / 8)
defines the size of a SHA-256 hash value in bytes
Definition at line 52 of file sha256.h.
Typedef Documentation
sha256_hash_t
sha256_hash_t
SHA-256 hash value type.
A variable of this type may hold the hash value produced by the sha256_ctx2hash(sha256_hash_t *dest, const sha256_ctx_t *state) function.
Definition at line 72 of file sha256.h.
Function Documentation
sha256()
void sha256 (sha256_hash_t * dest, const void * msg, uint32_t length)
simple SHA-256 hashing function for direct hashing
This function automaticaly hashes a given message of arbitary length with the SHA-256 hashing algorithm.
Parameters
dest pointer to the location where the hash value is going to be written to
msg pointer to the message thats going to be hashed
length_b length of the message in bits
Definition at line 226 of file sha256.c.
References SHA256_BLOCK_BITS, sha256_ctx2hash(), sha256_init(), sha256_lastBlock(), and sha256_nextBlock().
sha256_ctx2hash()
void sha256_ctx2hash (sha256_hash_t * dest, const sha256_ctx_t * state)
convert the hash state into the hash value This function reads the context and writes the hash value to the destination
Parameters
dest pointer to the location where the hash value should be written
state pointer to the SHA-256 hash context
Definition at line 242 of file sha256.c.
Referenced by sha256().
sha256_init()
void sha256_init (sha256_ctx_t * state)
sh256_init initialises a sha256 context for hashing. sh256_init c initialises the given sha256 context for hashing
initialise a SHA-256 context
Parameters
state pointer to a sha256 context
Returns
none
This function sets a sha256_ctx_t to the initial values for hashing.
Parameters
state pointer to the SHA-256 hashing context
Definition at line 63 of file sha256.c.
Referenced by entropium_addEntropy(), entropium_getRandomBlock(), and sha256().
sha256_lastBlock()
void sha256_lastBlock (sha256_ctx_t * state, const void * block, uint16_t length)
function to process the last block being hashed
finalize the context with the given block
Parameters
state Pointer to the context in which this block should be processed.
block Pointer to the message wich should be hashed.
length is the length of only THIS block in BITS not in bytes! bits are big endian, meaning high bits come first. if you have a message with bits at the end, the byte must be padded with zeros
This function finalizes the SHA-256 hash context by processing the given block of variable length.
Parameters
state pointer to the SHA-256 hash context
block pointer to the block of fixed length (512 bit = 64 byte)
length_b the length of the block in bits
Definition at line 177 of file sha256.c.
References SHA256_BLOCK_BITS, SHA256_BLOCK_BYTES, and sha256_nextBlock().
Referenced by entropium_addEntropy(), entropium_getRandomBlock(), and sha256().
sha256_nextBlock()
void sha256_nextBlock (sha256_ctx_t * state, const void * block)
update the context with a given block
block must be 512 Bit = 64 Byte long !!!
This function updates the SHA-256 hash context by processing the given block of fixed length.
Parameters
state pointer to the SHA-256 hash context
block pointer to the block of fixed length (512 bit = 64 byte)
Definition at line 123 of file sha256.c.
Referenced by entropium_addEntropy(), sha256(), and sha256_lastBlock().