ebs-cryptolib: cryptolib/sha256/sha256.c File Reference
sha256.c File Reference
SHA-256 implementation.
#include <stdint.h>
#include <string.h>
#include <platform/romem.h>
#include "sha256.h"
Macros
#define LITTLE_ENDIAN
#define sha256_init_vector_T_p ROMEM_TABLE_P(sha256_init_vector)
#define CH(x, y, z) (((x) & (y)) ^ ((~(x)) & (z)))
#define MAJ(x, y, z) (((x) & (y)) ^ ((x) & (z)) ^ ((y) & (z)))
#define SIGMA0(x) (rotr32((x), 2) ^ rotr32((x), 13) ^ rotr32((x), 22))
#define SIGMA1(x) (rotr32((x), 6) ^ rotr32((x), 11) ^ rotr32((x), 25))
#define SIGMA_a(x) (rotr32((x), 7) ^ rotr32((x), 18) ^ ((x) >> 3))
#define SIGMA_b(x) (rotr32((x), 17) ^ rotr32((x), 19) ^ ((x) >> 10))
#define k_T_p ROMEM_TABLE_P(k)
Functions
void sha256_init (sha256_ctx_t *state)
sh256_init initialises a sha256 context for hashing. sh256_init c initialises the given sha256 context for hashing
void sha256_nextBlock (sha256_ctx_t *state, const void *block)
update the context with a given block
void sha256_lastBlock (sha256_ctx_t *state, const void *block, uint16_t length)
function to process the last block being hashed
void sha256 (sha256_hash_t *dest, const void *msg, uint32_t length)
simple SHA-256 hashing function for direct hashing
void sha256_ctx2hash (sha256_hash_t *dest, const sha256_ctx_t *state)
convert the hash state into the hash value This function reads the context and writes the hash value to the destination
Detailed Description
SHA-256 implementation.
Author
Daniel Otte
Date
16.05.2006
License:
GPL
Definition in file sha256.c.
Function Documentation
sha256()
void sha256 (sha256_hash_t * dest, const void * msg, uint32_t length_b)
simple SHA-256 hashing function for direct hashing
This function automaticaly hashes a given message of arbitary length with the SHA-256 hashing algorithm.
Parameters
dest pointer to the location where the hash value is going to be written to
msg pointer to the message thats going to be hashed
length_b length of the message in bits
Definition at line 226 of file sha256.c.
References SHA256_BLOCK_BITS, sha256_ctx2hash(), sha256_init(), sha256_lastBlock(), and sha256_nextBlock().
sha256_ctx2hash()
void sha256_ctx2hash (sha256_hash_t * dest, const sha256_ctx_t * state)
convert the hash state into the hash value This function reads the context and writes the hash value to the destination
Parameters
dest pointer to the location where the hash value should be written
state pointer to the SHA-256 hash context
Definition at line 242 of file sha256.c.
Referenced by sha256().
sha256_init()
void sha256_init (sha256_ctx_t * state)
sh256_init initialises a sha256 context for hashing. sh256_init c initialises the given sha256 context for hashing
initialise a SHA-256 context
Parameters
state pointer to a sha256 context
Returns
none
This function sets a sha256_ctx_t to the initial values for hashing.
Parameters
state pointer to the SHA-256 hashing context
Definition at line 63 of file sha256.c.
Referenced by entropium_addEntropy(), entropium_getRandomBlock(), and sha256().
sha256_lastBlock()
void sha256_lastBlock (sha256_ctx_t * state, const void * block, uint16_t length_b)
function to process the last block being hashed
finalize the context with the given block
Parameters
state Pointer to the context in which this block should be processed.
block Pointer to the message wich should be hashed.
length is the length of only THIS block in BITS not in bytes! bits are big endian, meaning high bits come first. if you have a message with bits at the end, the byte must be padded with zeros
This function finalizes the SHA-256 hash context by processing the given block of variable length.
Parameters
state pointer to the SHA-256 hash context
block pointer to the block of fixed length (512 bit = 64 byte)
length_b the length of the block in bits
Definition at line 177 of file sha256.c.
References SHA256_BLOCK_BITS, SHA256_BLOCK_BYTES, and sha256_nextBlock().
Referenced by entropium_addEntropy(), entropium_getRandomBlock(), and sha256().
sha256_nextBlock()
void sha256_nextBlock (sha256_ctx_t * state, const void * block)
update the context with a given block
block must be 512 Bit = 64 Byte long !!!
This function updates the SHA-256 hash context by processing the given block of fixed length.
Parameters
state pointer to the SHA-256 hash context
block pointer to the block of fixed length (512 bit = 64 byte)
Definition at line 123 of file sha256.c.
Referenced by entropium_addEntropy(), sha256(), and sha256_lastBlock().